# Generated by Django 5.0 on 2024-01-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0003_alter_inmueble_foto_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='ruta_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
