# Generated by Django 5.0 on 2024-01-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0005_inmueble_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='categorias',
            field=models.CharField(blank=True, choices=[('unifamiliar', 'unifamiliar'), ('apartamento', 'apartamento'), ('mansion', 'mansión'), ('casa de campo', 'casa de Campo'), ('casa de playa', 'casa de Playa')], max_length=20),
        ),
    ]
